export default [
    {
      id: '1',
      avatar: 'https://cdn2.iconfinder.com/data/icons/avatars-99/62/avatar-370-456322-512.png',
      author: 'THUNDERX',
      title: 'Jadwal MSC 2021 Fase Grup: Dimulai 7 Juni, EVOS Legends Hadapi Todak di Hari Pertama',
      image: 'https://cdn-2.tstatic.net/surabaya/foto/bank/images/msc-2021-logoo.jpg',
      date: '6 Juni 2021',
      description: 'Berikut Jadwal MSC 2021 fase grup pertama, EVOS Legends hadapi Todak di hari pertama, Bigetron dihadang Blacklist International.\n\nFase Grup Pertama MSC 2021 atau Mobile Legends Southeast Asia Cup akan dimulai pada Senin (7/6/2021).\n\nSebanyak 12 tim bakal memperebutkan gelar juara menjadi tim terbaik di rahan esports Mobile Legends dalam cakupan Asia Tenggara.\n\nPada turnamen MSC 2021 kali ini, Indonesia bakal diwakili oleh dua tim yaitu EVOS Legends dan Bigetron Alpha.\n\nDua tim tersebut merupakan juara dan runner up di turnamen skala nasional yaitu MPL Season 7 lalu.\n\nUntuk diketahui, EVOS Legends dan Bigetron Alpha tergabung dalam grup yang berbeda.\n\nEVOS bakal mengawali fase grup pertama di Grup B melawan Todak (Malaysia) dan Cyber Exe (Vietnam).\n\nSementara Bigetron Alpha bakal menghadapi lawan berat di Grup C yaitu Blacklist International (Filipina) dan Impunity KH (Kamboja).\n\nMelansir situs resmi MSC 2021, EVOS dan BTR Alpha bakal langsung dihadapkan lawan berat di hari pembuka, Senin (7/6/2021) mendatang.',
    },
    {
      id: '2',
      avatar: 'https://cdn4.vectorstock.com/i/1000x1000/06/18/male-avatar-profile-picture-vector-10210618.jpg',
      author: 'Offmeta',
      title: '3 Hero Mobile Legends untuk Counter Meta Haram Bane-Faramis',
      image: 'https://asset.indosport.com/article/image/q/80/284420/logo_mobile_legends-169.jpg?w=750&h=423',
      date: '5 Juni 2021',
      description: 'Game eSports Mobile Legends baru-baru ini dikejutkan adanya meta haram hero Bane dan Faramis yang mampu push turret dengan cepat.\n\nMeta combo haram Bane dan Faramis sedang menjadi percincangan hangat di jagat media sosial khususnya di Tiktok. Setelah ditelusuri, ternyata meta ini pertama kali muncul di turnamen Mobile Legends, MPL Filipina Season 7.\n\nPara pro player Mobile Legends asal Filipina memang terkenal berani bereksperimen di level kompetitif. Tidak heran jika banyak para pemain game Mobile Legends yang meniru meta yang mereka buat.\n\nSebelumnya, pro player filipina sempat membuat meta yaitu Diggie Feeder dan beberapa waktu lalu ada meta baru bernama Nice One Baby.\n\nTidak heran jika banyak para pemain game Mobile Legends yang meniru meta yang mereka buat.\n\nMenanggapi soal adanya meta haram Bane dan Faramis, para penggemar game Mobile Legends tidak perlu cemas. Moonton sebagai pengembang game moba tidak akan menciptakan hero tanpa memiliki kelemahan.\n\nBerikut INDOSPORT telah merangkum 3 hero yang efektik sebagai counter Bane-Faramis:\n\n1. Akai\nAkai merupakan hero role tank yang memilikiskill crowd control yang mematikan. Ketika hero Bane, Faramis melakukan split push, Akai bisa menggunakan skill tiganya Akai untuk menangkal mereka mamasuki turret.\n\nSkill ini bernama (Hurricane Dance), Akai memutar tubuhnya selama 3.5 detik dan memberikan efek knockback kepada semua target yang dikenai.\n\n2. Valir\nValir merupakan salah satu hero mage yang memiliki Crowd Control yang sangat tinggi. Skill bernama (Searing Torrent) membuat Valir dapat mendorong target menjauhi dirinya, memberikan efek knockback dan juga efek slow sebesar 25%.\n\nKalian bisa menggunakan skill ini untuk menggagalkan split push yang dilakukan oleh hero Bane, Faramis. Caranya dengan mendorong mereka menjauhi turret ketika mereka sedang melakukan split push.\n\n3. Tigreal\nHero Tank satu ini kerap digunakan untuk meng-counter meta split push hero Bane-Faramis di Land Of Down. Skill dua dan tiga Tigreal sangat mematikan karena mampu memberikan efek knockback, airborne hingga efek stun.\n\nSuatu target tidak akan dapat bergerak selama lima detik ketika Tigreal menggunakan combo skill-nya. Kalian bisa mendorong Bane dan Faramis menjauhi turret menggunakan skill duanya Tigreal, lalu gunakan lagi skill dua untuk memberikan efek airborne.\n\nKemudian, yang terakhir gunakanlah skill tiga untuk memberikan efek stun selama 1.5 detik. Dengan efek crowd control sekuat itu, mereka berdua tidak akan bisa menghancurkan turret secara paksa.',
    },
    {
      id: '3',
      avatar: 'https://static.vecteezy.com/system/resources/previews/002/275/847/non_2x/male-avatar-profile-icon-of-smiling-caucasian-man-vector.jpg',
      author: 'MANISO',
      title: 'KLAIM KODE Redeem Mobile Legends Sekarang 5 April 2021, Buruan Klaim Kode Redeem ML Hari Ini',
      image: 'https://assets.pikiran-rakyat.com/crop/0x0:0x0/x/photo/2021/06/03/1516635513.jpg',
      date: '4 Juni 2021',
      description: 'Seperti kita ketahui kalau Mobile Legends Bang Bang (MLBB) merupakan mobile game dari Moonton.\n\nGame ini belakangan sangat banyak digandrungi masyarakat dari berbagai kalangan.\n\nApalagi Moonton selalu memberikan kode redeem ML secara berkala, tak terkecuali pada kode redeem ML 5 April 2021 di bawah ini.\n\nUntuk diketahui, Mobile Legends adalah permainan strategi seru dan kerjasama tim. Game ini selalu menarik untuk diikuti.\n\nHari ini, tanggal 5 April 2021, kode redeem ML kembali diluncurkan untuk mengklaim skin gratis.\n\nDimainkan oleh Banyak Kalangan Mulai dari kalangan ojol, siswa sekolah, pekerja swasta, bahkan hingga artis, semua bermain permainan seru yang satu ini.\n\nPilihan hero yang cukup banyak dan permainan yang cukup mudah dipahami ditengarai jadi alasan utamanya.\n\nNah, agar semakin seru, tentu menggunakan skin menjadi pilihan beberapa orang.',
    },
];